name: workspace-nouveau

services:
  workspace:
    image: INTO-CPS-Association/dtaas-workspace-nouveau
    build:
      context: .
      args:
        CODE_SERVER_PORT: 8080
        JUPYTER_NOTEBOOK_PORT: 8888
        JUPYTER_LAB_PORT: 8899
        MAIN_USER: dtaas-user-1
    ports:
      - "6901:6901"
      - "8080:8080"
      - "8888:8888"
      - "8899:8899"
    shm_size: 512m
    volumes:
      - ./persistent_dir:/Workspace
    develop:
      watch:
        - path: .
          action: rebuild
