services:
  traefik:
    image: traefik:v3.6.4
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dynamic/tls.yml:/etc/traefik/dynamic/tls.yml"
      - "./certs:/etc/traefik-certs"
    networks:
      - frontend
      - users

  client:
    image: intocps/dtaas-web:latest
    restart: unless-stopped
    volumes:
      - "./dtaas/client.js:/dtaas/client/build/env.js"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`${SERVER_DNS:-localhost}`) && PathPrefix(`/`)"
      - "traefik.http.routers.client.tls=true"
      - "traefik.http.routers.client.middlewares=traefik-forward-auth"
      - "traefik.http.services.client.loadbalancer.server.port=4000"
    networks:
      - frontend

  user1:
    image: workspace:latest
    restart: unless-stopped
    depends_on:
      minio-server-setup:
        condition: service_completed_successfully
    build:
      context: .
    environment:
      - MAIN_USER=${USERNAME1}
      - USER_STORE_ENDPOINT=http://minio-server:9000
      - COMMON_STORE_ENDPOINT=http://minio-server:9000
      - USER_STORE_KEY_ID=${USER_1_STORE_KEY_ID}
      - USER_STORE_SECRET_KEY=${USER_1_STORE_SECRET_KEY}
      - COMMON_STORE_KEY_ID=${USER_1_STORE_KEY_ID}
      - COMMON_STORE_SECRET_KEY=${USER_1_STORE_SECRET_KEY}
      - USER_BUCKET=${USER_1_BUCKET}
      - COMMON_BUCKET=${COMMON_BUCKET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.u1.rule=Host(`${SERVER_DNS:-localhost}`) && PathPrefix(`/${USERNAME1}`)"
      - "traefik.http.routers.u1.tls=true"
      - "traefik.http.routers.u1.middlewares=traefik-forward-auth"
    networks:
      - users
    links:
      - minio-server:minio-server

  user2:
    image: mltooling/ml-workspace-minimal:0.13.2
    restart: unless-stopped
    volumes:
      - "./persistent_dir/common:/workspace/common"
      - "./persistent_dir/${USERNAME2}:/workspace"
    environment:
      - AUTHENTICATE_VIA_JUPYTER=
      - WORKSPACE_BASE_URL=${USERNAME2}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.u2.rule=Host(`${SERVER_DNS:-localhost}`) && PathPrefix(`/${USERNAME2}`)"
      - "traefik.http.routers.u2.tls=true"
      - "traefik.http.routers.u2.middlewares=traefik-forward-auth"
    networks:
      - users

  user3:
    image: workspace:latest
    restart: unless-stopped
    depends_on:
      minio-server-setup:
        condition: service_completed_successfully
    build:
      context: .
    environment:
      - MAIN_USER=${USERNAME3}
      - USER_STORE_ENDPOINT=http://minio-server:9000
      - COMMON_STORE_ENDPOINT=http://minio-server:9000
      - USER_STORE_KEY_ID=${USER_3_STORE_KEY_ID}
      - USER_STORE_SECRET_KEY=${USER_3_STORE_SECRET_KEY}
      - COMMON_STORE_KEY_ID=${USER_3_STORE_KEY_ID}
      - COMMON_STORE_SECRET_KEY=${USER_3_STORE_SECRET_KEY}
      - USER_BUCKET=${USER_3_BUCKET}
      - COMMON_BUCKET=${COMMON_BUCKET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.u3.rule=Host(`${SERVER_DNS:-localhost}`) && PathPrefix(`/${USERNAME3}`)"
      - "traefik.http.routers.u3.tls=true"
      - "traefik.http.routers.u3.middlewares=traefik-forward-auth"
    networks:
      - users
    links:
      - minio-server:minio-server

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:latest
    restart: unless-stopped
    volumes:
      - "./dtaas/conf:/conf"
    environment:
      - LOG_LEVEL=trace
      - DEFAULT_PROVIDER=generic-oauth
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=${OAUTH_URL}/oauth/authorize
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=${OAUTH_URL}/oauth/token
      - PROVIDERS_GENERIC_OAUTH_USER_URL=${OAUTH_URL}/api/v4/user
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - PROVIDERS_GENERIC_OAUTH_SCOPE=read_user
      - SECRET= "${OAUTH_SECRET}"
      - CONFIG=/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redirect.entryPoints=web-secure"
      - "traefik.http.routers.redirect.rule=Host(`${SERVER_DNS:-localhost}`) && PathPrefix(`/_oauth`)"
      - "traefik.http.routers.redirect.middlewares=traefik-forward-auth"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
    networks:
      - frontend
      - users

  minio-server:
    image: minio/minio:latest
    container_name: minio-server
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 6
  
  minio-server-setup:
    image: minio/mc:latest
    container_name: minio-server-setup
    depends_on:
      minio-server:
        condition: service_healthy
      script-generator:
        condition: service_completed_successfully
    entrypoint: > 
      /bin/sh -c "
      /tmp/syssec/initial-setup.sh &&
      /tmp/syssec/setup-common-bucket.sh &&
      /tmp/syssec/setup-user1-bucket.sh &&
      /tmp/syssec/setup-user3-bucket.sh &&
      /tmp/syssec/setup-user1.sh &&
      /tmp/syssec/setup-user3.sh
      "
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - setup-scripts:/tmp/syssec
    links:
      - minio-server:minio-server

  script-generator:
    image: bash:latest
    container_name: script-generator
    command: >
      /usr/local/bin/bash -c "
      apk add --no-cache coreutils &&
      apk add --no-cache sed &&
      cp /tmp/input/initial-setup.sh /output/initial-setup.sh &&
      cp /tmp/input/setup-bucket.sh /output/setup-common-bucket.sh &&
      cp /tmp/input/setup-bucket.sh /output/setup-user1-bucket.sh &&
      cp /tmp/input/setup-user.sh /output/setup-user1.sh &&
      cp /tmp/input/user-policy.json /output/${USER_1_STORE_KEY_ID}.json &&
      cp /tmp/input/setup-bucket.sh /output/setup-user3-bucket.sh &&
      cp /tmp/input/setup-user.sh /output/setup-user3.sh &&
      cp /tmp/input/user-policy.json /output/${USER_3_STORE_KEY_ID}.json &&
      sed -i 's|{MINIO_ROOT_USER}|${MINIO_ROOT_USER}|g' /output/initial-setup.sh &&
      sed -i 's|{MINIO_ROOT_PASSWORD}|${MINIO_ROOT_PASSWORD}|g' /output/initial-setup.sh &&
      sed -i 's|{BUCKET_NAME}|${USER_1_BUCKET}|g' /output/setup-user1-bucket.sh &&
      sed -i 's|{BUCKET_NAME}|${USER_3_BUCKET}|g' /output/setup-user3-bucket.sh &&
      sed -i 's|{BUCKET_NAME}|${COMMON_BUCKET}|g' /output/setup-common-bucket.sh &&
      sed -i 's|{USER_STORE_KEY_ID}|${USER_1_STORE_KEY_ID}|g' /output/setup-user1.sh &&
      sed -i 's|{USER_STORE_SECRET_KEY}|${USER_1_STORE_SECRET_KEY}|g' /output/setup-user1.sh &&
      sed -i 's|{USER_STORE_KEY_ID}|${USER_3_STORE_KEY_ID}|g' /output/setup-user3.sh &&
      sed -i 's|{USER_STORE_SECRET_KEY}|${USER_3_STORE_SECRET_KEY}|g' /output/setup-user3.sh &&
      sed -i 's|{USER_BUCKET}|${USER_1_BUCKET}|g' /output/${USER_1_STORE_KEY_ID}.json &&
      sed -i 's|{COMMON_BUCKET}|${COMMON_BUCKET}|g' /output/${USER_1_STORE_KEY_ID}.json &&
      sed -i 's|{USER_BUCKET}|${USER_3_BUCKET}|g' /output/${USER_3_STORE_KEY_ID}.json &&
      sed -i 's|{COMMON_BUCKET}|${COMMON_BUCKET}|g' /output/${USER_3_STORE_KEY_ID}.json &&
      chmod +x /output/*
      "
    volumes:
      - ./syssec:/tmp/input:ro
      - setup-scripts:/output

volumes:
  setup-scripts:


networks:
  frontend:
    name: dtaas-frontend
  users:
    name: dtaas-users
