name: workspace-traefik-secure-tls

services:
  traefik:
    image: traefik:v3.6.4
    restart: unless-stopped
    command:
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic/tls.yml:/etc/traefik/dynamic/tls.yml:ro
      - ./certs:/etc/traefik-certs:ro
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`${SERVER_DNS:-localhost}`) &&
        (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.entryPoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=traefik-forward-auth"
    networks:
      - frontend
      - users

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - DEFAULT_PROVIDER=generic-oauth
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=${OAUTH_URL}/oauth/authorize
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=${OAUTH_URL}/oauth/token
      - PROVIDERS_GENERIC_OAUTH_USER_URL=${OAUTH_URL}/api/v4/user
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - PROVIDERS_GENERIC_OAUTH_SCOPE=read_user openid profile email
      - SECRET=${OAUTH_SECRET}
      - AUTH_HOST=${SERVER_DNS:-localhost}
      - COOKIE_DOMAIN=${SERVER_DNS:-localhost}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-forward-auth.entryPoints=websecure"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`${SERVER_DNS:-localhost}`) && PathPrefix(`/_oauth`)"
      - "traefik.http.routers.traefik-forward-auth.tls=true"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
    networks:
      - frontend
      - users

  user1:
    image: workspace-nouveau:latest
    restart: unless-stopped
    build:
      context: .
    environment:
      - MAIN_USER=user1
    volumes:
      - ./persistent_dir/user1:/workspace
      - ./persistent_dir/common:/workspace/common
    shm_size: 512m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.u1.entryPoints=websecure"
      - "traefik.http.routers.u1.rule=Host(`${SERVER_DNS:-localhost}`) && PathPrefix(`/user1`)"
      - "traefik.http.routers.u1.tls=true"
      - "traefik.http.routers.u1.middlewares=traefik-forward-auth"
    networks:
      - users

  user2:
    image: mltooling/ml-workspace-minimal:0.13.2
    restart: unless-stopped
    environment:
      - AUTHENTICATE_VIA_JUPYTER=
      - WORKSPACE_BASE_URL=user2
    volumes:
      - ./persistent_dir/user2:/workspace
      - ./persistent_dir/common:/workspace/common
    shm_size: "512m"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.u2.entryPoints=websecure"
      - "traefik.http.routers.u2.rule=Host(`${SERVER_DNS:-localhost}`) && PathPrefix(`/user2`)"
      - "traefik.http.routers.u2.tls=true"
      - "traefik.http.routers.u2.middlewares=traefik-forward-auth"
    networks:
      - users

networks:
  frontend:
    name: dtaas-frontend
  users:
    name: dtaas-users
